### ISSUE TITLE
invalid module format occurs for e1000 and igb

### ISSUE THREAD

**Issue by PeterSuh-Q3** [pocopico/redpill-modules#1]
pocopico, your modulepack with kernel 4.4.302+ used for Apollo Lake DSM 7.2.0-64216.
I used it in VMWARE FUSION virtual environment and this VM only needs e1000.

****As in the log below, invalid module format occurs for e1000 and igb.
In your module e1000 is missing and igb is included.
e1000 is the module I compiled.****

The same thing happens with both modules.

This is my compilation environment.
I configured the kernel compilation environment on Ubuntu 16.04 as below.

1. Install kernel compiler
sudo apt-get install build-essential libncurses-dev bison flex libssl-dev libelf-dev

2. Install Kernel Package Manager (Unnecessary)
sudo apt-get install linux-generic

3. Download the Synology Toolchain kernel source code, extract it, and add it to your PATH. (Unnecessary)
sudo -i
wget https://global.synologydownload.com/download/ToolChain/toolchain/7.2-63134/Intel%20x86%20Linux%204.4.302%20%28Apollolake%29/apollolake-gcc1220_glibc236_x86_64-GPL.txz
tar -xJvf apollolake-gcc1220_glibc236_x86_64-GPL.txz
export PATH=$(pwd)/x86_64-pc-linux-gnu/bin:$PATH

4. Install docker

5. Compile arpl-modules.
cd /root/arpl*/src
Adjust PLATFORMS file version [4.4.180 -> 4.4.302]
./complie.sh

In this process, it seems that fabio's 7.2 module compilation library is automatically used.

**And the path for DSM download in config.json uses beta instead of relesase .
The path below is correct.**

https://global.download.synology.com/download/DSM/beta/7.2/64216/DSM_DS1019%2B_64216.pat

My repo was replaced like below.

cd redpill-load
cd config
sed -i "s/release\\/7.2.0/beta\\/7.2/g" ./*/7.2.0-64216/config.json 

**And if you don't build a new bsp for each model, KP will occur.**

-------------------------------------------------------

Running "check-all-modules.sh" for modprobe->on_boot
apollolake
4.4.302
modules.alias.4.json
Copying kmod to /bin/
'kmod' -> '/bin/kmod'
Copying sed,jq,lspci files to /sbin/
'sed' -> '/usr/sbin/sed'
'jq' -> '/usr/sbin/jq'
'lspci' -> '/usr/sbin/lspci'
Copying lspci libraries to /lib/
'libz.so.1' -> '/lib/libz.so.1'
'libudev.so.1' -> '/lib/libudev.so.1'
'libattr.so.1' -> '/lib/libattr.so.1'
'libcap.so.2' -> '/lib/libcap.so.2'
link modprobe to kmod
modprobe: FATAL: Module ata_piix not found.
insmod: can't insert '/lib/modules/ata_piix.ko': No such file or directory
Found IDE Controller : pciid 8086d00007111  Required Extension : Searching for matching extension for ata_piix
Found VGA Controller : pciid 15add00000405  Required Extension : No matching extension
[   13.895774] mptbase: Unknown rela relocation: 4
modprobe: ERROR: could not insert 'mptspi': Exec format error
[   15.448962] mptspi: Unknown symbol mpt_deregister (err 0)
[   15.449774] mptspi: Unknown symbol mpt_reset_deregister (err 0)
[   15.450560] mptspi: Unknown symbol mptscsih_host_attrs (err 0)
[   15.451333] mptspi: Unknown symbol mptscsih_qcmd (err 0)
[   15.451925] mptspi: Unknown symbol mptscsih_bios_param (err 0)
[   15.452610] mptspi: Unknown symbol mptscsih_io_done (err 0)
[   15.453261] mptspi: Unknown symbol mptscsih_slave_configure (err 0)
[   15.487313] mptspi: Unknown symbol mpt_config (err 0)
[   15.487914] mptspi: Unknown symbol mptscsih_taskmgmt_complete (err 0)
[   15.488704] mptspi: Unknown symbol mptscsih_ioc_reset (err 0)
[   15.489404] mptspi: Unknown symbol mpt_free_msg_frame (err 0)
[   15.490051] mptspi: Unknown symbol mptscsih_remove (err 0)
[   15.490700] mptspi: Unknown symbol mptscsih_bus_reset (err 0)
[   15.491378] mptspi: Unknown symbol mptscsih_is_phys_disk (err 0)
[   15.492047] mptspi: Unknown symbol spi_display_xfer_agreement (err 0)
[   15.492827] mptspi: Unknown symbol mptscsih_host_reset (err 0)
[   15.493544] mptspi: Unknown symbol spi_release_transport (err 0)
[   15.494226] mptspi: Unknown symbol mpt_put_msg_frame (err 0)
[   15.495288] mptspi: Unknown symbol mpt_register (err 0)
[   15.496257] mptspi: Unknown symbol mpt_event_deregister (err 0)
[   15.497363] mptspi: Unknown symbol mpt_findImVolumes (err 0)
[   15.498251] mptspi: Unknown symbol mptscsih_scandv_complete (err 0)
[   15.499288] mptspi: Unknown symbol mptscsih_resume (err 0)
[   15.499956] mptspi: Unknown symbol mptscsih_raid_id_to_num (err 0)
[   15.500689] mptspi: Unknown symbol mpt_event_register (err 0)
[   15.501383] mptspi: Unknown symbol mptscsih_event_process (err 0)
[   15.502079] mptspi: Unknown symbol mptscsih_suspend (err 0)
[   15.502816] mptspi: Unknown symbol mptscsih_slave_destroy (err 0)
[   15.503615] mptspi: Unknown symbol mptscsih_change_queue_depth (err 0)
[   15.537917] mptspi: Unknown symbol spi_attach_transport (err 0)
[   15.538726] mptspi: Unknown symbol mptscsih_shutdown (err 0)
[   15.539542] mptspi: Unknown symbol mpt_get_msg_frame (err 0)
[   15.540238] mptspi: Unknown symbol mptscsih_dev_reset (err 0)
[   15.541000] mptspi: Unknown symbol mpt_attach (err 0)
[   15.541615] mptspi: Unknown symbol mpt_reset_register (err 0)
[   15.542364] mptspi: Unknown symbol mptscsih_info (err 0)
[   15.542986] mptspi: Unknown symbol mptscsih_abort (err 0)
[   15.543692] mptspi: Unknown symbol mpt_HardResetHandler (err 0)
[   15.544458] mptspi: Unknown symbol spi_dv_device (err 0)
[   15.545064] mptspi: Unknown symbol mptscsih_show_info (err 0)
[   15.545792] mptspi: Unknown symbol mptscsih_IssueTaskMgmt (err 0)
[   15.550556] mptspi: Unknown symbol mpt_deregister (err 0)
[   15.551421] mptspi: Unknown symbol mpt_reset_deregister (err 0)
[   15.552601] mptspi: Unknown symbol mptscsih_host_attrs (err 0)
[   15.553733] mptspi: Unknown symbol mptscsih_qcmd (err 0)
[   15.588144] mptspi: Unknown symbol mptscsih_bios_param (err 0)
[   15.588866] mptspi: Unknown symbol mptscsih_io_done (err 0)
[   15.589557] mptspi: Unknown symbol mptscsih_slave_configure (err 0)
[   15.590297] mptspi: Unknown symbol mpt_config (err 0)
[   15.590870] mptspi: Unknown symbol mptscsih_taskmgmt_complete (err 0)
[   15.591625] mptspi: Unknown symbol mptscsih_ioc_reset (err 0)
[   15.592267] mptspi: Unknown symbol mpt_free_msg_frame (err 0)
[   15.592951] mptspi: Unknown symbol mptscsih_remove (err 0)
[   15.593598] mptspi: Unknown symbol mptscsih_bus_reset (err 0)
[   15.594242] mptspi: Unknown symbol mptscsih_is_phys_disk (err 0)
[   15.594960] mptspi: Unknown symbol spi_display_xfer_agreement (err 0)
[   15.595723] mptspi: Unknown symbol mptscsih_host_reset (err 0)
[   15.596420] mptspi: Unknown symbol spi_release_transport (err 0)
[   15.597089] mptspi: Unknown symbol mpt_put_msg_frame (err 0)
[   15.597756] mptspi: Unknown symbol mpt_register (err 0)
[   15.598374] mptspi: Unknown symbol mpt_event_deregister (err 0)
[   15.599036] mptspi: Unknown symbol mpt_findImVolumes (err 0)
[   15.599717] mptspi: Unknown symbol mptscsih_scandv_complete (err 0)
[   15.600474] mptspi: Unknown symbol mptscsih_resume (err 0)
[   15.601099] mptspi: Unknown symbol mptscsih_raid_id_to_num (err 0)
[   15.601829] mptspi: Unknown symbol mpt_event_register (err 0)
[   15.602521] mptspi: Unknown symbol mptscsih_event_process (err 0)
[   15.603216] mptspi: Unknown symbol mptscsih_suspend (err 0)
[   15.603897] mptspi: Unknown symbol mptscsih_slave_destroy (err 0)
[   15.637990] mptspi: Unknown symbol mptscsih_change_queue_depth (err 0)
[   15.638771] mptspi: Unknown symbol spi_attach_transport (err 0)
[   15.639518] mptspi: Unknown symbol mptscsih_shutdown (err 0)
[   15.640560] mptspi: Unknown symbol mpt_get_msg_frame (err 0)
[   15.641507] mptspi: Unknown symbol mptscsih_dev_reset (err 0)
[   15.642166] mptspi: Unknown symbol mpt_attach (err 0)
[   15.642830] mptspi: Unknown symbol mpt_reset_register (err 0)
[   15.643559] mptspi: Unknown symbol mptscsih_info (err 0)
[   15.644210] mptspi: Unknown symbol mptscsih_abort (err 0)
[   15.644899] mptspi: Unknown symbol mpt_HardResetHandler (err 0)
[   15.645722] mptspi: Unknown symbol spi_dv_device (err 0)
[   15.646398] mptspi: Unknown symbol mptscsih_show_info (err 0)
[   15.647066] mptspi: Unknown symbol mptscsih_IssueTaskMgmt (err 0)
insmod: can't insert '/lib/modules/mptspi.ko': unknown symbol in module, or unknown parameter
Found SCSI Controller : pciid 1000d00000030  Required Extension : Searching for matching extension for mptspi
**_[   16.111373] e1000: Unknown rela relocation: 4
modprobe: ERROR: could not insert 'e1000': Exec format error
[   17.125911] e1000: Unknown rela relocation: 4
[   17.130463] e1000: Unknown rela relocation: 4
insmod: can't insert '/lib/modules/e1000.ko': invalid module format_**
Found Ethernet Interface : pciid 8086d0000100f Required Extension : Searching for matching extension for e1000
Found SATA Controller : pciid 15add000007e0  Required Extension : No matching extension
insmod: can't insert '/lib/modules/ahci.ko': No such file or directory
Found SATA Controller : pciid 8086d00005ae3  Required Extension : Searching for matching extension for ahci
Found SATA Controller : pciid 1b4bd00009215  Required Extension : No matching extension
[   18.306501] igb: Unknown rela relocation: 4
**_modprobe: ERROR: could not insert 'igb': Exec format error
[   19.319058] igb: Unknown rela relocation: 4
[   19.323848] igb: Unknown rela relocation: 4
insmod: can't insert '/lib/modules/igb.ko': invalid module format_**
Found Ethernet Interface : pciid 8086d00001539 Required Extension : Searching for matching extension for igb
[   19.361312] igb: Unknown rela relocation: 4
modprobe: ERROR: could not insert 'igb': Exec format error
[   20.372592] igb: Unknown rela relocation: 4
[   20.377305] igb: Unknown rela relocation: 4
insmod: can't insert '/lib/modules/igb.ko': invalid module format
Found Ethernet Interface : pciid 8086d00001539 Required Extension : Searching for matching extension for igb
Ran "check-all-modules.sh" for modprobe->on_boot - exit=0
Running "install-nvme-cache.sh" for nvme-cache->on_boot
System is booting
nvme-cache - early
Ran "install-nvme-cache.sh" for nvme-cache->on_boot - exit=0
Running "boot-wait.sh" for thethorgroup.boot-wait->on_boot
Ran "boot-wait.sh" for thethorgroup.boot-wait->on_boot - exit=0
:: Executing "on_boot" custom scripts ... [  OK  ]
Extensions processed
[   20.415975] etxhci_hcd: Unknown symbol usb_hcd_resume_root_hub (err 0)
[   20.417371] etxhci_hcd: Unknown symbol usb_hcd_pci_probe (err 0)
[   20.418343] etxhci_hcd: Unknown symbol usb_hcd_unlink_urb_from_ep (err 0)
[   20.419312] etxhci_hcd: Unknown symbol usb_hc_died (err 0)
[   20.420101] etxhci_hcd: Unknown symbol usb_wakeup_notification (err 0)
[   20.421048] etxhci_hcd: Unknown symbol usb_hcd_irq (err 0)
[   20.421815] etxhci_hcd: Unknown symbol usb_hcd_check_unlink_urb (err 0)
[   20.422776] etxhci_hcd: Unknown symbol usb_hcd_pci_pm_ops (err 0)
[   20.423651] etxhci_hcd: Unknown symbol usb_control_msg (err 0)
[   20.424501] etxhci_hcd: Unknown symbol usb_hcd_pci_shutdown (err 0)
[   20.425403] etxhci_hcd: Unknown symbol usb_hcd_link_urb_to_ep (err 0)
[   20.426327] etxhci_hcd: Unknown symbol usb_hcd_is_primary_hcd (err 0)
[   20.427268] etxhci_hcd: Unknown symbol usb_acpi_power_manageable (err 0)
[   20.428228] etxhci_hcd: Unknown symbol usb_put_hcd (err 0)
[   20.429008] etxhci_hcd: Unknown symbol usb_hcd_giveback_urb (err 0)
[   20.429915] etxhci_hcd: Unknown symbol usb_hcd_poll_rh_status (err 0)
[   20.430847] etxhci_hcd: Unknown symbol usb_acpi_set_power_state (err 0)
[   20.431793] etxhci_hcd: Unknown symbol usb_hcd_pci_remove (err 0)
[   20.432674] etxhci_hcd: Unknown symbol usb_remove_hcd (err 0)
[   20.433508] etxhci_hcd: Unknown symbol usb_add_hcd (err 0)
[   20.434354] etxhci_hcd: Unknown symbol usb_create_shared_hcd (err 0)
[   20.435303] etxhci_hcd: Unknown symbol usb_root_hub_lost_power (err 0)
[   20.441768] etxhci_hcd: Unknown symbol usb_hcd_resume_root_hub (err 0)
[   20.442775] etxhci_hcd: Unknown symbol usb_hcd_pci_probe (err 0)
[   20.443668] etxhci_hcd: Unknown symbol usb_hcd_unlink_urb_from_ep (err 0)
[   20.444676] etxhci_hcd: Unknown symbol usb_hc_died (err 0)
[   20.445530] etxhci_hcd: Unknown symbol usb_wakeup_notification (err 0)
[   20.447350] etxhci_hcd: Unknown symbol usb_hcd_irq (err 0)
[   20.448471] etxhci_hcd: Unknown symbol usb_hcd_check_unlink_urb (err 0)
[   20.449694] etxhci_hcd: Unknown symbol usb_hcd_pci_pm_ops (err 0)
[   20.450917] etxhci_hcd: Unknown symbol usb_control_msg (err 0)
[   20.452019] etxhci_hcd: Unknown symbol usb_hcd_pci_shutdown (err 0)
[   20.453166] etxhci_hcd: Unknown symbol usb_hcd_link_urb_to_ep (err 0)
[   20.454354] etxhci_hcd: Unknown symbol usb_hcd_is_primary_hcd (err 0)
[   20.455724] etxhci_hcd: Unknown symbol usb_acpi_power_manageable (err 0)
[   20.457124] etxhci_hcd: Unknown symbol usb_put_hcd (err 0)
[   20.457942] etxhci_hcd: Unknown symbol usb_hcd_giveback_urb (err 0)
[   20.458862] etxhci_hcd: Unknown symbol usb_hcd_poll_rh_status (err 0)
[   20.459793] etxhci_hcd: Unknown symbol usb_acpi_set_power_state (err 0)
[   20.460756] etxhci_hcd: Unknown symbol usb_hcd_pci_remove (err 0)
[   20.461651] etxhci_hcd: Unknown symbol usb_remove_hcd (err 0)
[   20.462515] etxhci_hcd: Unknown symbol usb_add_hcd (err 0)
[   20.463352] etxhci_hcd: Unknown symbol usb_create_shared_hcd (err 0)
[   20.464333] etxhci_hcd: Unknown symbol usb_root_hub_lost_power (err 0)
insmod: can't insert '/lib/modules/etxhci-hcd.ko': unknown symbol in module, or unknown parameter
[   20.471747] apollolake_synobios: module license 'Synology Inc.' taints kernel.
[   20.473970] Disabling lock debugging due to kernel taint
[   20.475176] apollolake_synobios: Unknown rela relocation: 4
[   20.482363] BUG: unable to handle kernel paging request at ffffffffa0356fb8
[   20.483961] IP: [<ffffffffa00072ff>] shim_bios_module+0x2f/0x5c0 [redpill]
[   20.485023] PGD 99e0d067 PUD 99e0e063 PMD 8c42a067 PTE 0
[   20.485829] Oops: 0000 [#1] SMP 
[   20.486322] Modules linked in: apollolake_synobios(PO+)
[   20.487091] CPU: 3 PID: 6547 Comm: insmod Tainted: P           OE   4.4.302+ #64216
[   20.488173] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 11/12/2020
[   20.489682] task: ffff88008dbf1a00 ti: ffff88008f9e4000 task.ti: ffff88008f9e4000
[   20.490752] RIP: 0010:[<ffffffffa00072ff>]  [<ffffffffa00072ff>] shim_bios_module+0x2f/0x5c0 [redpill]
[   20.492083] RSP: 0018:ffff88008f9e7d08  EFLAGS: 00010246
[   20.492834] RAX: ffffffffa0356f80 RBX: ffffffffa0373140 RCX: ffffffffa0357cc0
[   20.493849] RDX: 0000000000000000 RSI: ffffffffa0373140 RDI: ffffffffa0009760
[   20.494873] RBP: ffff88008f9e7d10 R08: ffffffff810bd450 R09: 0000000000000000
[   20.495912] R10: ffff880094132d10 R11: fefefefefefefeff R12: 0000000000000001
[   20.497000] R13: ffffffffa0373140 R14: 00000000fffffffb R15: ffffffff81847820
[   20.498098] FS:  00007fe15611b740(0000) GS:ffff88009acc0000(0000) knlGS:0000000000000000
[   20.499282] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   20.500121] CR2: ffffffffa0356fb8 CR3: 00000000921e9000 CR4: 00000000003606f0
[   20.501245] Stack:
[   20.501557]  0000000000000000 ffff88008f9e7d30 ffffffffa0007efc 0000000000000000
[   20.502696]  0000000000000001 ffff88008f9e7d70 ffffffff8106e02a ffffffff81844d20
[   20.503832]  ffffffffa0373158 ffffffffa0373140 0000000000000000 0000000000000000
[   20.505005] Call Trace:
[   20.505445]  [<ffffffffa0007efc>] bios_module_notifier_handler+0x6c/0x110 [redpill]
[   20.506773]  [<ffffffff8106e02a>] blocking_notifier_call_chain+0x7a/0x90
[   20.507983]  [<ffffffff810c1803>] load_module+0x1a03/0x2300
[   20.508970]  [<ffffffff8116556d>] ? __vmalloc+0x8d/0xc0
[   20.509885]  [<ffffffff810c221b>] SYSC_init_module+0x11b/0x150
[   20.510815]  [<ffffffff810c22e9>] SyS_init_module+0x9/0x10
[   20.511602]  [<ffffffff8159124a>] entry_SYSCALL_64_fastpath+0x1e/0x93
[   20.512517] Code: 84 ac 05 00 00 48 85 c9 0f 84 a3 05 00 00 55 48 8d 02 48 89 e5 48 8d 64 24 f8 48 89 15 23 71 00 00 48 8b 15 5c 71 00 00 48 85 d2 <48> 8b 48 38 0f 85 f8 02 00 00 48 89 0d e8 72 00 00 48 c7 05 3d 
[   20.515982] RIP  [<ffffffffa00072ff>] shim_bios_module+0x2f/0x5c0 [redpill]
[   20.516978]  RSP <ffff88008f9e7d08>
[   20.517479] CR2: ffffffffa0356fb8
[   20.517951] ---[ end trace f1451dc7ef8ee76a ]---
Killed
Starting /usr/syno/bin/synocfgen...
/usr/syno/bin/synocfgen returns 255
[   20.525837] Module [apollolake_synobios] is removed. 
rmmod: can't unload module 'apollolake_synobios': Device or resource busy
Insert synorbd kernel module
Insert synofsbd kernel module
Insert sha256 kernel module
Assemble args: -u 3200aa10:2f92ab20:3017a5a8:c86610be /dev/sda1 /dev/sdb1
[   20.591639] md: md0 stopped.
[   20.592819] md: bind<sdb1>
[   20.593501] md: bind<sda1>
[   20.596063] md/raid1:md0: active with 2 out of 16 mirrors
[   20.598453] md0: detected capacity change from 0 to 8589869056
mdadm: /dev/md0 has been started with 2 drives (out of 16).
Partition Version=9
[   20.653756] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
[   20.665755] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
 /sbin/e2fsck exists, checking /dev/md0... 
e2fsck 1.44.1 (24-Mar-2018)
/sbin/e2fsck -yvf returns 0
Mounting /dev/md0 /tmpRoot
[   20.897580] EXT4-fs (md0): couldn't mount as ext3 due to feature incompatibilities
[   20.907550] EXT4-fs (md0): mounted filesystem with ordered data mode. Opts: (null)
------------upgrade
Begin upgrade procedure
[   21.012900] loop: module loaded
[   21.039525] EXT4-fs (loop0): couldn't mount as ext3 due to feature incompatibilities
[   21.062047] EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)
Failed to found any patch
No upgrade file found
End upgrade procedure
============upgrade
------------bootup-smallupdate
Failed to AssertFileKeyValueEqual
  value1: /etc.defaults/synoinfo.conf:unique -> synology_apollolake_918+
  value2: /tmpRoot/etc.defaults/synoinfo.conf:unique => synology_broadwellnk_3622xs+
Skip bootup smallupdate, because root is not matched to junior
============bootup-smallupdate
Failed to AssertFileKeyValueEqual
  value1: /etc.defaults/synoinfo.conf:unique -> synology_apollolake_918+
  value2: /tmpRoot/etc.defaults/synoinfo.conf:unique => synology_broadwellnk_3622xs+
Exit on error [7] root not matched with junior...
Mon Mar 20 01:19:31 UTC 2023
/dev/md0 /tmpRoot ext4 rw,relatime,data=ordered 0 0
none /sys/kernel/debug debugfs rw,relatime 0 0
[   22.045463] VFS: opened file in mnt_point: (/dev), file: (/urandom), comm: (ttyd)
[   22.046733] VFS: opened file in mnt_point: (/dev), file: (/null), comm: (sh)
[   22.047844] VFS: opened file in mnt_point: (/dev), file: (/null), comm: (sh)
umount: can't unmount /dev: Device or resource busy
umount: /etc/mtab: No such file [   22.062316] VFS: opened file in mnt_point: (/dev), file: (/urandom), comm: (ttyd)
or directory
[   22.063506] VFS: opened file in mnt_point: (/dev), file: (/null), comm: (sh)
[   22.064650] VFS: opened file in mnt_point: (/dev), file: (/null), comm: (sh)
linuxrc.syno failed on 7
starting pid 7217, tty '': '/etc/rc'
:: Starting /etc/rc
:: Mounting procfs ... [  OK  ]
:: Mounting tmpfs ... [  OK  ]
:: Mounting devtmpfs ... [FAILED]
:: Mounting devpts ... [  OK  ]
:: Mounting sysfs ... [  OK  ]
[   22.138584] md: md1 stopped.
[   22.139883] md: bind<sdb2>
[   22.140490] md: bind<sda2>
[   22.142615] md/raid1:md1: active with 2 out of 16 mirrors
[   22.143752] md1: detected capacity change from 0 to 2147418112
[   22.155874] Adding 2097084k swap on /dev/md1.  Priority:-1 extents:1 across:2097084k 
:: Loading module usb-common ... [  OK  ]
:: Loading module usbcore[   22.254193] ACPI: bus type USB registered
[   22.254802] usbcore: registered new interface driver usbfs
[   22.255645] usbcore: registered new interface driver hub
[   22.256509] usbcore: registered new interface driver ethub
[   22.257480] usbcore: registered new device driver usb
 ... [  OK  ]
:: Loading module mdio ... [  OK  ]
:: Loading module fat ... [  OK  ]
:: Loading module vfat ... [  OK  ]
:: Loading module udp_tunnel ... [  OK  ]
:: Loading module ip6_udp_tunnel ... [  OK  ]
:: Loading module vxlan ... [  OK  ]
:: Loading module e1000e[   22.378987] e1000e: Intel(R) PRO/1000 Network Driver - 3.8.4-NAPI
[   22.379983] e1000e: Copyright(c) 1999 - 2020 Intel Corporation.
 ... [  OK  ]
:: Loading module i2c-algo-bit ... [  OK  ]
:: Loading module igb[   22.395088] Intel(R) Gigabit Ethernet Linux Driver - version 5.7.2
[   22.396063] Copyright(c) 2007 - 2021 Intel Corporation.
[   22.396866] igb: probe of 0001:02:00.0 failed with error -5
[   22.397683] igb: probe of 0001:03:00.0 failed with error -5
 ... [  OK  ]
:: Loading module be2net ... [  OK  ]
:: Loading module ixgbe[   22.423909] Intel(R) 10GbE PCI Express Linux Network Driver - version 5.13.4
[   22.424878] Copyright(c) 1999 - 2021 Intel Corporation.
 ... [  OK  ]
:: Loading module r8168 ... [  OK  ]
:: Loading module r8125 ... [  OK  ]
:: Loading module i40e[   22.452987] i40e: Unknown symbol i40e_ndo_set_vf_port_vlan (err 0)
[   22.454112] i40e: Unknown symbol i40e_ptp_set_increment (err 0)
[   22.455053] i40e: Unknown symbol i40e_ptp_rx_hang (err 0)
[   22.455814] i40e: Unknown symbol i40e_ptp_set_ts_config (err 0)
[   22.456572] i40e: Unknown symbol i40e_free_vfs (err 0)
[   22.457216] i40e: Unknown symbol i40e_ptp_stop (err 0)
[   22.457843] i40e: Unknown symbol i40e_ndo_set_vf_mac (err 0)
[   22.458538] i40e: Unknown symbol i40e_ndo_set_vf_spoofchk (err 0)
[   22.459292] i40e: Unknown symbol i40e_reset_all_vfs (err 0)
[   22.459947] i40e: Unknown symbol i40e_vc_process_vf_msg (err 0)
[   22.460708] i40e: Unknown symbol i40e_ptp_get_pins (err 0)
[   22.461394] i40e: Unknown symbol i40e_ptp_tx_hang (err 0)
[   22.462024] i40e: Unknown symbol i40e_alloc_vfs (err 0)
[   22.462700] i40e: Unknown symbol i40e_pci_sriov_configure (err 0)
[   22.463555] i40e: Unknown symbol i40e_ptp_alloc_pins (err 0)
[   22.464414] i40e: Unknown symbol i40e_ptp_init (err 0)
[   22.465087] i40e: Unknown symbol i40e_ndo_get_vf_config (err 0)
[   22.465995] i40e: Unknown symbol i40e_vc_notify_reset (err 0)
[   22.466887] i40e: Unknown symbol i40e_get_vf_stats (err 0)
[   22.467711] i40e: Unknown symbol i40e_restore_all_vfs_msi_state (err 0)
[   22.468730] i40e: Unknown symbol i40e_ptp_rx_hwtstamp (err 0)
[   22.469419] i40e: Unknown symbol i40e_ptp_tx_hwtstamp (err 0)
[   22.470077] i40e: Unknown symbol i40e_vc_notify_vf_reset (err 0)
[   22.470813] i40e: Unknown symbol i40e_reset_vf (err 0)
[   22.471425] i40e: Unknown symbol i40e_ptp_get_ts_config (err 0)
[   22.472102] i40e: Unknown symbol i40e_restore_ingress_egress_mirror (err 0)
[   22.472935] i40e: Unknown symbol i40e_ptp_save_hw_time (err 0)
[   22.473629] i40e: Unknown symbol i40e_ndo_set_vf_bw (err 0)
[   22.474299] i40e: Unknown symbol i40e_vc_process_vflr_event (err 0)
[   22.475022] i40e: Unknown symbol i40e_ndo_set_vf_link_state (err 0)
[   22.475762] i40e: Unknown symbol i40e_ndo_set_vf_trust (err 0)
[   22.476447] i40e: Unknown symbol i40e_vc_notify_link_state (err 0)
[   22.477169] i40e: Unknown symbol i40e_ptp_set_pins_ioctl (err 0)
[   22.481698] i40e: Unknown symbol i40e_ndo_set_vf_port_vlan (err 0)
[   22.482455] i40e: Unknown symbol i40e_ptp_set_increment (err 0)
[   22.483157] i40e: Unknown symbol i40e_ptp_rx_hang (err 0)
[   22.483782] i40e: Unknown symbol i40e_ptp_set_ts_config (err 0)
[   22.484511] i40e: Unknown symbol i40e_free_vfs (err 0)
[   22.485116] i40e: Unknown symbol i40e_ptp_stop (err 0)
[   22.485751] i40e: Unknown symbol i40e_ndo_set_vf_mac (err 0)
[   22.486827] i40e: Unknown symbol i40e_ndo_set_vf_spoofchk (err 0)
[   22.488487] i40e: Unknown symbol i40e_reset_all_vfs (err 0)
[   22.489563] i40e: Unknown symbol i40e_vc_process_vf_msg (err 0)
[   22.490711] i40e: Unknown symbol i40e_ptp_get_pins (err 0)
[   22.491631] i40e: Unknown symbol i40e_ptp_tx_hang (err 0)
[   22.492289] i40e: Unknown symbol i40e_alloc_vfs (err 0)
[   22.492888] i40e: Unknown symbol i40e_pci_sriov_configure (err 0)
[   22.493610] i40e: Unknown symbol i40e_ptp_alloc_pins (err 0)
[   22.494283] i40e: Unknown symbol i40e_ptp_init (err 0)
[   22.494870] i40e: Unknown symbol i40e_ndo_get_vf_config (err 0)
[   22.495561] i40e: Unknown symbol i40e_vc_notify_reset (err 0)
[   22.496239] i40e: Unknown symbol i40e_get_vf_stats (err 0)
[   22.496904] i40e: Unknown symbol i40e_restore_all_vfs_msi_state (err 0)
[   22.497724] i40e: Unknown symbol i40e_ptp_rx_hwtstamp (err 0)
[   22.498482] i40e: Unknown symbol i40e_ptp_tx_hwtstamp (err 0)
[   22.499217] i40e: Unknown symbol i40e_vc_notify_vf_reset (err 0)
[   22.499957] i40e: Unknown symbol i40e_reset_vf (err 0)
[   22.500590] i40e: Unknown symbol i40e_ptp_get_ts_config (err 0)
[   22.501361] i40e: Unknown symbol i40e_restore_ingress_egress_mirror (err 0)
[   22.502276] i40e: Unknown symbol i40e_ptp_save_hw_time (err 0)
[   22.502989] i40e: Unknown symbol i40e_ndo_set_vf_bw (err 0)
[   22.503689] i40e: Unknown symbol i40e_vc_process_vflr_event (err 0)
[   22.504461] i40e: Unknown symbol i40e_ndo_set_vf_link_state (err 0)
[   22.505184] i40e: Unknown symbol i40e_ndo_set_vf_trust (err 0)
[   22.505935] i40e: Unknown symbol i40e_vc_notify_link_state (err 0)
[   22.506833] i40e: Unknown symbol i40e_ptp_set_pins_ioctl (err 0)
 ... [FAILED]
:: Loading module sunrpc[   22.533665] RPC: Registered named UNIX socket transport module.
[   22.534934] RPC: Registered udp transport module.
[   22.536088] RPC: Registered tcp transport module.
[   22.536855] RPC: Registered tcp NFSv4.1 backchannel transport module.
 ... [  OK  ]
:: Loading module grace ... [  OK  ]
:: Loading module lockd ... [  OK  ]
:: Loading module nfs ... [  OK  ]
:: Loading module nfsv3 ... [  OK  ]
:: Loading module leds-lp3943 ... [  OK  ]

**Comment by pocopico** [comment]
We are trying to figure out why this is happening. Not a simple solution though.

**Comment by PeterSuh-Q3** [comment]
It was not a problem that could be easily solved.

Before I compiled the 7.2 kernel 4.4.302 module
I witnessed the process of downloading and preparing the syno-compiler 7.2 toolkit and toolchain for Docker from fabio's repo.

https://github.com/fbelavenuto/arpl/tree/main/docker/syno-compiler

Download a very large file.

Revision 7.2 Beta is already using revision 64216 and
It's a slightly older revision than this, but even though the toolkit's revision 63134 is specified as kernel 4.4.302, it should be clear.

https://archive.synology.com/download/ToolChain/toolchain/7.2-63134

The kernel version of the 7.2 beta can be checked directly through a user who has updated from a genuine Synology, but 4.4.302 will definitely be correct.

It is assumed that this problem, which has now been identified, is not a kernel version mismatch issue.

**Comment by wjz304** [comment]
@PeterSuh-Q3 
Due to the high restrictions on email and IP in xpenology.com, I am unable to reply on xpenology.com. I am sorry.

I tested a few, and most of them were okay. i40e. ko reported the same error as you.
I think you should ignore the issue of i40e for now. It can be resolved later.
![image](https://user-images.githubusercontent.com/5615843/235329491-93ed7676-de19-4aea-bb7b-2ae1c96d560c.png)
![image](https://user-images.githubusercontent.com/5615843/235329516-eb2adae7-8f64-4715-bec1-88bd09baa205.png)

**Comment by wjz304** [comment]
@PeterSuh-Q3 
![image](https://user-images.githubusercontent.com/5615843/235330134-c52d0b81-b392-4d96-b669-c7882b12f283.png)
Check if the file hash is correct? I can insmod it.

**Comment by PeterSuh-Q3** [comment]
> @PeterSuh-Q3 ![image](https://user-images.githubusercontent.com/5615843/235330134-c52d0b81-b392-4d96-b669-c7882b12f283.png) Check if the file hash is correct? I can insmod it.


I seem to have found the cause.

https://raw.githubusercontent.com/pocopico/rp-ext/master/redpillprod/releases/redpill-4.4.302plus-$PLATFORM.tgz

I used pocopico's lkm , but it doesn't seem to compile correctly for 4.4.302.

After changing wiz304 to your lkm and building, no errors occur.

thank you
