### ISSUE TITLE
.ko file for the latest kernel

### ISSUE THREAD

**Issue by Kamilake** [pocopico/redpill-modules#5]
## Can I get an en version of the 4.4.302 kernel version or build it myself?
![image](https://github.com/pocopico/redpill-modules/assets/15166740/24316c46-8ade-4af6-a96f-fbe93e65c47d)
## What I need: `bnx2x.ko` `mdio.ko`
Currently the latest version in this repository is 4.4.180. But I want to add modules from 4.4.302 to my kernel (I own a physical 1821+).
Is there somewhere I can find the source code? Or if you're due for an update, I'll be patient and wait!

**Comment by pocopico** [comment]
The modules are already compiled for v1000 platform 

https://github.com/pocopico/redpill-modules/tree/master/v1000-4.4.302

**Comment by Kamilake** [comment]
> The modules are already compiled for v1000 platform

oh my god, that works!!! the problem is completely solved I love you

![image](https://github.com/pocopico/redpill-modules/assets/15166740/01a2df13-5472-45e3-9f55-88b74d269a0f)
![image](https://github.com/pocopico/redpill-modules/assets/15166740/de73b440-b1d8-44bd-a075-e54839e671c5)
